export const states = [
  { key: 'AC', name: 'Acre' },
  { key: 'AL', name: 'Alagoas' },
  { key: 'AP', name: 'Amapá' },
  { key: 'AM', name: 'Amazonas' },
  { key: 'BA', name: 'Bahia' },
  { key: 'CE', name: 'Ceará' },
  { key: 'ES', name: 'Espirito Santo' },
  { key: 'GO', name: 'Goiás' },
  { key: 'MA', name: 'Manaus' },
  { key: 'MT', name: 'Mato Grosso' },
  { key: 'MS', name: 'Mato Grosso do Sul' },
  { key: 'MG', name: 'Minas Gerais' },
  { key: 'PA', name: 'Pará' },
  { key: 'PB', name: 'Paraíba' },
  { key: 'PR', name: 'Paraná' },
  { key: 'PE', name: 'Pernambuco' },
  { key: 'RJ', name: 'Rio de Janeiro' },
  { key: 'RS', name: 'Rio Grande do Sul' },
  { key: 'RN', name: 'Rio Grande do Norte' },
  { key: 'RO', name: 'Rondônia' },
  { key: 'RR', name: 'Roraima' },
  { key: 'SC', name: 'Santa Catarina' },
  { key: 'SP', name: 'São Paulo' },
  { key: 'SE', name: 'Sergipe' },
  { key: 'TO', name: 'Tocantins' },
];